#!/bin/sh

# htdig - small shell-script to update the htdig-databases of all
#         websites on the machine.
#
#         To be run periodically, e.g. by cron every night. stdout and
#         stderr should be (combined and) piped through squeeze (htdig
#         2>&1 | squeeze).
#
#         All dirs in /var/www/ are considered - dirs are skipped if
#         there is no conf/htdig.conf or htdig/db.
#
# Copyright (C) 2003-2004, aparte, Magenta. by Adam Sjøgren <asjo@aparte.dk>.
# Under the GPL.

HOSTNAME="$(hostname)"

for d in /var/www/*/; do
    test -d ${d}conf || continue
    test -e ${d}conf/htdig.conf || continue
    test -d ${d}htdig/db || continue

    site="$(basename $d)"
    echo "#Indexing ${site} on ${HOSTNAME}"
    /var/www/obvius/cron/rundig ${d} "$@"
done
